# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55e70b96401148bfd4b57a006bbbf59c0d4aeb148eb3f8ca0575432f2d21e83e315edfb4349bd677956cef3f91d42dbbef89508f07b8c298724ff0929ffa20ef

test:
  secret_key_base: 2347981cd8d0812842b699a3961dcb431fdbf9ae357cb4699e6146a57b7885a9449afb0c71998559b65d50072254cb371ef4214f6d4eb6548175661e61ec8b44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
